services:

frontend:
    container_name: it01-animals-frontend
    image: ict302-animals-frontend:latest
    ports:
      - 80:80
    restart: always

  backend:
  container_name: it01-animals-backend
    image: ict302-animals-backend:latest
    ports:
      - 5173:5173
    restart: always
    volumes:
      - app_storage:/it01/app-storage

  db:
  container_name: it01-animals-mysql
    image: mysql:latest
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: WildVision!
      MYSQL_DATABASE: it01-animals
    volumes:
      - "C:/docker_data/mysql_data:/var/lib/mysql"
    restart: always

volumes:
  app_storage:
      